# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run(github has defines a lot of events)
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# now it is time to define the works that should be done:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-first-job:
  # for a job, you have to define the runner
  # The ubuntu-latest label currently uses the Ubuntu 22.04 runner image.
    runs-on: ubuntu-latest
    steps:
      # the name of the first step
      - name: print greeting
        # the commands for the first step
        run: echo "hello world!"

      # the name of the second step
      - name: print goodbye
        run: echo "good bye"

